var/lib/pulse2/clients/win32/downloads/python-3.6.5.exe
var/lib/pulse2/clients/win32/downloads/python-3.6.5-amd64.exe
var/lib/pulse2/clients/win32/downloads/python_modules/pywin32-223.win32-py3.6.exe
var/lib/pulse2/clients/win32/downloads/python_modules/pywin32-223.win-amd64-py3.6.exe
var/lib/pulse2/clients/win32/downloads/python_modules/PyQt5-5.10.1-5.10.1-cp35.cp36.cp37.cp38-none-win32.whl
var/lib/pulse2/clients/win32/downloads/python_modules/PyQt5-5.10.1-5.10.1-cp35.cp36.cp37.cp38-none-win_amd64.whl
